### ISSUE TITLE
Logic Engine doesn't handle missing values gracefully 

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#44]
The only non-trivial logic engine config we have is in the `resource_request channel`.  As you can see, there are several places which rely on pandas queries to get values to compare in the logical expressions.  If for whatever reason the row is missing from the PANDAS data frame (for instance there is a key error in looking up `AWS_Billing_Rate[AWS_Billing_Rate['accountName'] == 'Fermilab']`), then the logic engine throws an error, fortunately not a fatal one. 

We need either a way to incorporate a test for existence of the value we need, or some way to help the DE recover in a suitable way when the value is not available.

```yaml
facts: {
  publish_requests: "(True)",
  allow_grid: "(True)",
  allow_lcf: "(True)",
  allow_gce: "(True)",
  allow_aws: "(True)",
  awswithininstburnrate: "financial_params.iloc[0].target_aws_vm_burn_rate>AWS_Burn_Rate.iloc[0].BurnRate",
  awswithinbillburnrate: "financial_params.iloc[0].target_aws_bill_burn_rate>AWS_Billing_Rate[AWS_Billing_Rate['accountName']=='Fermilab'].iloc[0].costRatePerHourInLastSixHours",
  awsabovebalance: "financial_params.iloc[0].target_aws_balance<AWS_Billing_Info[AWS_Billing_Info['AccountName']=='Fermilab'].iloc[0].Balance",
  gcewithininstburnrate: "financial_params.iloc[0].target_gce_vm_burn_rate>GCE_Burn_Rate.iloc[0].BurnRate",
  gceabovebalance: "financial_params.iloc[0].target_gce_balance<GCE_Billing_Info.iloc[0].Balance",
  uscmsnerscbelowlimit: "Nersc_Allocation_Info[Nersc_Allocation_Info['uname']=='uscms'].iloc[0].user_amount_charged<Nersc_Allocation_Info[Nersc_Allocation_Info['uname']=='uscms'].iloc[0].user_limit",
}

**Comment by StevenCTimm** [comment]
Hopefully this will all be addressed in the total rewrite of the Logic Engine that is scheduled.

**Comment by StevenCTimm** [comment]
Logic Engine has totally been rewritten in 1.6 branch (not yet merged to trunk).  now is time to look at this again.

**Comment by knoepfel** [comment]
@StevenCTimm, I imagine there can be at least two scenarios to consider:

1. The fact expression has been misspecified, and it will always raise an exception due to a (e.g.) misspelled variable.
2. The fact expression is well-formed, but the preconditions are not always satisfied--i.e. the expression is not flexible enough to allow for circumstances when a particular piece of data is or is not present.

Item 1 represents a failure which should take a channel offline--in principle, though, a more robust `produces` and `consumes` system will address it.  

Item 2, however, is primarily what you're dealing with.  I think the solution there will be to use Python's conditional statements: `a if A else b`.  Otherwise, we just need to make sure the error message is appropriately propagated to the log file if it isn't already.

Thoughts?

**Comment by StevenCTimm** [comment]
Yes we are basically concerned with #2. If you look at the stock resource_request.jsonnet  you see that we 
are implicitly doing operations on the pandas data frame blocks, and sometimes (most likely when the billing routines are not functioning correctly) those operations return a Nan rather than the int or float.  Would be interested to see how the if/else conditionals in python would fit into these configuration files and if it will provide a solution.  Goal is that if the value is missing the fact should end up false.

**Comment by knoepfel** [comment]
@StevenCTimm, thanks.  Something for your consideration--the fact expressions all use `.iloc[0]` syntax.  Makes me think that a Pandas data frame is not the right type if you're always having to select a specific entry in the frame.  Ideally, we'd have something more like:

```yaml
facts: {
  publish_requests: "(True)",
  allow_grid: "(True)",
  allow_lcf: "(True)",
  allow_gce: "(True)",
  allow_aws: "(True)",
  awswithininstburnrate: "financial_params.target_aws_vm_burn_rate > AWS_Burn_Rate.BurnRate",
  awswithinbillburnrate: "financial_params.target_aws_bill_burn_rate > AWS_Billing_Rate['Fermilab'].costRatePerHourInLastSixHours",
  awsabovebalance: "financial_params.target_aws_balance < AWS_Billing_Info['Fermilab'].Balance",
  gcewithininstburnrate: "financial_params.target_gce_vm_burn_rate > GCE_Burn_Rate.BurnRate",
  gceabovebalance: "financial_params.target_gce_balance < GCE_Billing_Info.Balance",
  uscmsnerscbelowlimit: "Nersc_Allocation_Info['uscms'].user_amount_charged < Nersc_Allocation_Info['uscms'].user_limit",
}
```
I know the syntax above isn't quite right, but isn't that conceptually what we're after?  How much breakage would happen if we migrated away from the Pandas data frame in this case?
